### ISSUE TITLE
test/data/names and test/data/orbs should be merged

### ISSUE THREAD

**Issue by Droogans** [PlaytestersKitchen/match-three-js#19]
Is there an instance where `names.js` and `orbs.js` aren't used together?

If not, I'd like to see them merged as an object, ala

``` js
export const boards = {
    'a simple row match': [
        [ 1, 2, 3, 4, 5 ],
        [ 5, 1, 2, 3, 4 ],
        [ 4, 5, 1, 2, 3 ],
        [ 3, 6, 6, 6, 2 ],
        [ 2, 3, 4, 5, 1 ]
    ],
    'a simple column match': [
        [ 1, 2, 3, 4, 5 ],
        [ 5, 1, 2, 3, 4 ],
        [ 4, 5, 1, 2, 6 ],
        [ 3, 4, 5, 1, 6 ],
        [ 2, 3, 4, 5, 6 ]
    ],
    'a simple row four-match': [
        [ 1, 2, 3, 4, 5 ],
        [ 5, 1, 2, 3, 4 ],
        [ 4, 5, 1, 2, 3 ],
        [ 3, 4, 5, 1, 2 ],
        [ 2, 6, 6, 6, 6 ]
    ],
    // ... and so on
};
```

Every test would pull them in together, and split them on key/value pairs themselves. It will make the test data easier to understand.

**Comment by rbcasperson** [comment]
I agree that this needs to be more understandable. The only thing is that `names` are the same for `orbs`, `foundMatches` and `combinedMatches`. Each of those can be changed to key/value pairs with the `names` as the keys, but if one is changed or added, it will have to be changed or added for all of those. 

What if they were all combined into one Object like this:

``` js
export const boardData = {
    'a simple row match': {
        'orbs': [
            [ 1, 2, 3, 4, 5 ],
            [ 5, 1, 2, 3, 4 ],
            [ 4, 5, 1, 2, 3 ],
            [ 3, 6, 6, 6, 2 ],
            [ 2, 3, 4, 5, 1 ]
        ],
        'foundMatches': [
            [[3, 1], [3, 2], [3, 3]]
        ],
        'combinedMatches': [
            [[3, 1], [3, 2], [3, 3]]
        ]
    },
    // and so on
}
```

**Comment by rbcasperson** [comment]
Although, `names` are also used in `evaluate`, `swap`, and `unmatch`, so that `boardData` Object would get very very dense.

**Comment by Droogans** [comment]
I think that's fine. It's much better than having two data files open side by side and comparing the start/end state of all test data.

This way it makes it much easier to see what kinds of expected inputs/outputs occur in the system all in one place.

**Comment by rbcasperson** [comment]
Okay sounds good.

**Comment by rbcasperson** [comment]
I added the [new file](https://github.com/PlaytestersKitchen/match-three-js/blob/finalize/babel/test/data/boardData.js) to the PR, but have not yet edited the test files. It is very thick as I figured, but it seems alright.
